In [1]:
import numpy as np
import pandas as pd
import streamlit as st
import csv
from collections import defaultdict
from numpy.random import default_rng as rng

import matplotlib.pyplot as plt
import matplotlib
import matplotlib.font_manager as fm
from os import path
from matplotlib.pyplot import figure
if 'Sarabun' not in [x.name for x in matplotlib.font_manager.fontManager.ttflist]:
    matplotlib.font_manager.fontManager.addfont('Sarabun-Regular.ttf')
matplotlib.rc('font', family='Sarabun')

from rsi_modules import *

mm3_url         = "https://docs.google.com/spreadsheets/d/1NrR5_OKyydIklO2UPBwHYdqI0Y_x1CaQxrie4OTFaDs/export?format=csv&gid=1475905714"
publication_url = "https://docs.google.com/spreadsheets/d/1NrR5_OKyydIklO2UPBwHYdqI0Y_x1CaQxrie4OTFaDs/export?format=csv&gid=2125519370"
theses_url      = "https://docs.google.com/spreadsheets/d/1NrR5_OKyydIklO2UPBwHYdqI0Y_x1CaQxrie4OTFaDs/export?format=csv&gid=609352385"

F = pd.read_csv(mm3_url)
publication = pd.read_csv(publication_url).fillna("")
theses = pd.read_csv(theses_url).fillna("")
theses = theses.drop_duplicates(subset=['รหัส (นักศึกษา)'], keep='last')

In [2]:
def MAIN_report_mm3(F):
    def calculate_teaching_hours_per_year(courses_year):
        for yr in courses_year.keys():  
            ajarn_teach_hr = defaultdict(float)
            for name_hr in courses_year[yr]:
                for name, hr in name_hr.items():
                    ajarn_teach_hr[name]+=hr
            courses_year[yr]=ajarn_teach_hr
        TEACH_TERM = pd.DataFrame(courses_year).fillna(0).reset_index()
        TEACH_TERM.rename(columns={'index':'name'}, inplace=True)
        hr_courses_year = MEMBERS.merge(TEACH_TERM, on='name', how='left').fillna(0)
        return hr_courses_year

    def identify_course_code_owner(course_owners):
        course_code_owner = defaultdict(list)
        for n,cw in zip(course_owners['name'],course_owners['owner_courses']):
            course_code = defaultdict(list)
            for c in cw:
                course_code[c[1]].append(c[0])
            course_code_owner[n] = course_code
        course_code_owner = pd.DataFrame(course_code_owner).T.fillna('0').reset_index().rename(columns={'index':'name'})
        course_code_owner = MEMBERS.merge(course_code_owner, on='name', how='left').fillna(0)
        return course_code_owner

    def count_owner_courses(course_code_owner):
        number_course_code_owner = defaultdict(list)
        for c in course_code_owner.columns:
            if c != 'name':
                for row in course_code_owner[c]:
                    if row != 0:
                        number_course_code_owner[c].append(len(row))
                    else:
                        number_course_code_owner[c].append(0)
                # number_course_code_owner[c] = course_code_owner[c]
        number_course_code_owner = pd.DataFrame(number_course_code_owner)
        number_course_code_owner['name']= course_code_owner['name']

        Member_Courses = MEMBERS.merge(number_course_code_owner, on='name', how='left').fillna(0)
        return Member_Courses
    

    # Main function
    f = remove_empty_columns(F)
    f = merge_multiple_academic_years(f)
    _, courses_year = courses(f)
    names = defaultdict(list)
    for aj,co,yr in zip(f['อาจารย์ผู้รับผิดชอบรายวิชา'],f['รหัสวิชา'],f['academic_year']):
        names[aj].append((co,yr))

    MEMBERS = pd.DataFrame(faculty_members()).rename(columns={0:'name'})
    course_owners = pd.DataFrame([names]).T.rename(columns={0:'owner_courses'}).reset_index().rename(columns={'index':'name'})

    # หาค่า ชั่วโมงสอน
    hr_courses_year = calculate_teaching_hours_per_year(courses_year)
    # หาค่า เจ้าของรหัสวิชา
    course_code_owner = identify_course_code_owner(course_owners)
    # หาค่า จำนวนรหัสวิชาที่เป็นเจ้าของ
    number_course_code_owner = count_owner_courses(course_code_owner)

    return hr_courses_year, course_code_owner, number_course_code_owner

In [3]:
F = pd.read_csv(mm3_url)
hr_courses_year, course_code_owner, number_course_code_owner = MAIN_report_mm3(F)

In [4]:
number_course_code_owner

,name,[2568]-เทอม 1,[2568]-เทอม 2,[2567]-เทอม 1,[2567]-เทอม 2
0,นพ.สมเกียรติ ลีละศิธร,0,0,0,0
1,พญ.วัชรา ริ้วไพบูลย์,0,0,0,0
2,ศ.ดร.ทวี เชื้อสุวรรณทวี,2,1,1,1
3,รศ.ดร.อาดัม นีละไพจิตร,1,1,1,1
4,รศ.ดร.ณัฏฐนียา โตรักษา,2,1,1,1
5,ผศ.ดร.อารี ภาวสุทธิไพศิฐ,2,1,1,1
6,ผศ.ดร.ธีรศักดิ์ ศรีสุรกุล,3,1,1,1
7,ผศ.ดร.เจนจิรา เจนจิตรวาณิช,3,1,1,1
8,ดร.รติรส จันทรสมดี,3,4,1,1
9,ดร.อิศวรา ศิริรุ่งเรือง,2,2,1,1
10,ดร.ธรรม จตุนาม,2,2,1,1
11,ดร.รุจิรา สงขาว,2,2,1,1
12,ดร.ปรเมศวร์ บุญยืน,7,2,1,1
13,ดร.ปกรณ์กิตติ์ ม่วงประสิทธิ์,1,4,1,1
14,ดร.สุนันทา ขลิบทอง,3,2,1,1
15,ดร.วรางคณา รัชตะวรรณ,2,2,1,1
16,ดร.ญาณิศา เนียรนาทตระกูล,3,3,1,1
17,ดร.สุภชาญ ตรัยตรึงศ์สกุล,0,0,0,0
18,ดร.วิษณุ นิตยธรรมกุล,0,0,0,0
19,พฤหัส เปรมสมิทธิ์,9,8,1,1
20,ราษฏร์ บุญญา,2,1,1,1
21,กุลยา ไทรงาม,0,0,0,0
22,ณัฐวิชญ์ ศุภสินธุ์,0,0,0,0
23,พชร นิลมณี,0,0,0,0
24,สิรินทรา ฤทธิเดช,0,0,0,0
25,สร้อยทอง หยกสุริยันต์,0,0,0,0
26,ภัทรานิษฐ สงประชา,0,0,0,0
27,อาจารย์พิเศษ (ภายนอกม.มหิดล),0,0,0,0
28,อาจารย์พิเศษ (ภายนอกคณะแพทย์ฯรามา ม.มหิดล),0,0,0,0

In [5]:
academic_yrs = ['[2568]-เทอม 1','[2568]-เทอม 2','[2567]-เทอม 1','[2567]-เทอม 2']

for i, ay in enumerate(academic_yrs):
    one_semester = pd.DataFrame()
    one_semester['name'] = hr_courses_year['name']
    one_semester['จำนวนชั่วโมงสอน'] = hr_courses_year[ay].round(2)
    one_semester['เจ้าของรหัสวิชา'] = course_code_owner[ay]
    one_semester['จำนวนรหัสวิชาที่เป็นเจ้าของ'] = number_course_code_owner[ay]
    one_semester.to_csv(f'teaching/teaching_{ay}.csv', index=False)

In [6]:
b = pd.DataFrame()
year = '2568'
for i, ay in enumerate([f'[{year}]-เทอม 1', f'[{year}]-เทอม 2']):
    a = pd.read_csv(f'teaching/teaching_{ay}.csv')
    b[i]=a['จำนวนชั่วโมงสอน']
b = pd.DataFrame(b.sum(axis=1)).rename(columns={0:'จำนวนชั่วโมงสอน'})
b['name'] = a['name']
c = pd.DataFrame()
c['name'] = b['name']
c['จำนวนชั่วโมงสอน'] = b['จำนวนชั่วโมงสอน']
c.to_csv(f'teaching/teaching_total_[{year}].csv', index=False)

In [7]:
round(c['จำนวนชั่วโมงสอน'].sum(axis=0))

2477

In [8]:
def get_author_value(publication):
    author_value = defaultdict(lambda: defaultdict(list))
    for n in faculty_members():
        for c in publication.columns:
            if 'ชื่ออาจารย์และสถานะผู้แต่งหนังสือ' in c:
                if n in c:
                    author_value[n][c]=0
            else:
                author_value[n][c]=0
    return author_value

In [9]:
author_value = get_author_value(publication)

for r in range(publication.shape[0]):
    temp = defaultdict(list)
# วนทีละบรรทัด
    for c,i in zip(publication.columns,publication.iloc[r]):
        if i != "":
            temp[c].append(i)
            if 'ชื่ออาจารย์และสถานะผู้แต่งหนังสือ' in c:
                name = c.replace('ชื่ออาจารย์และสถานะผู้แต่งหนังสือ [','').replace(']','')
    # break
    if 'collections.defaultdict' in str(type(author_value[name])):
        author_value[name] = pd.concat([pd.DataFrame([author_value[name]]),pd.DataFrame(temp)], axis=0, ignore_index=True).fillna(0)
    else:
        author_value[name] = pd.concat([pd.DataFrame(author_value[name]),pd.DataFrame(temp)], axis=0, ignore_index=True).fillna(0)

In [11]:
author_value[name]

,Timestamp,Email Address,ชื่อเรื่อง,ปีที่ตีพิมพ์ พศ. (คศ.),ประเภทบทความ [วารสารไทย (TCI1-TCI2)],ประเภทบทความ [วารสารนานาชาติ (Q1-Q4 หรืออื่นๆ)],ประเภทบทความ [ประชุมวิชาการระดับนานาชาติ (International Conference)],ประเภทบทความ [ประชุมวิชาการระดับชาติ (National Conference)],DOI หรือ URL ที่ตีพิมพ์,ระบุชื่อผู้แต่ง ที่เป็นFirst Author และ/หรือ Corresponding Author ที่ไม่ได้เป็นอาจารย์ในสถาบันราชสุดา หรือเป็นนักศึกษา โปรดใส่ สถานะผู้แต่ง เช่น สนธิ ลิ้ม (First Author) และ ศ.ดร.อำไพ ลอดยาว (Corresponding Author),ชื่ออาจารย์และสถานะผู้แต่งหนังสือ [ดร.วิษณุ นิตยธรรมกุล],ประเภทบทความ [Proceedings]
0,0,0,0,0,0.0,0,0.0,0.0,0,0,0,0.0
1,9/17/2025 23:02:31,vitsanu.nit@mahidol.ac.th,Using Virtual Reality and Conversational AI to...,2568 (2025),0.0,Q2,0.0,0.0,https://doi.org/10.11114/smc.v13i3.7683,Kridsanapong Lertbumroongchai (First Author),Corresponding Author,0.0
2,9/17/2025 23:05:36,vitsanu.nit@mahidol.ac.th,Development of Low-Cost PLC Training Kit for E...,2568 (2025),0.0,Q3,0.0,0.0,https://repository.li.mahidol.ac.th/handle/123...,Natt Siriwattananon (First Author),Corresponding Author,0.0
3,9/17/2025 23:08:50,vitsanu.nit@mahidol.ac.th,The 3D-POD Model for AI-Driven Institutional T...,2568 (2025),0.0,0,Q3,0.0,https://link.springer.com/chapter/10.1007/978-...,Sirinuch Sararuch (First Author),EIC,0.0
4,9/17/2025 23:14:34,vitsanu.nit@mahidol.ac.th,Online Learner Achievement and Satisfaction on...,2568 (2025),0.0,0,Q4,0.0,https://ieeexplore.ieee.org/document/11129412,Thakorn Yuvijit (First Author),EIC,0.0
5,11/4/2025 12:52:38,vitsanu.nit@mahidol.ac.th,Conversational AI-Powered VR Development Model...,2568 (2025),0.0,Q3,0,0.0,10.14569/IJACSA.2025.0161073,Jenasama Srihirun (First Author) และ Kridsanap...,EIC,0.0
6,11/4/2025 12:54:59,vitsanu.nit@mahidol.ac.th,Design of the System Architecture of Competenc...,2568 (2025),0.0,อื่นๆ,0,0.0,10.5539/hes.v15n4p422,Thongchai Arunchai (First Author),Corresponding Author,0.0
7,3/19/2026 13:12:42,vitsanu.nit@mahidol.ac.th,Development of Intelligent Advisory System wit...,2568 (2025),0.0,Q3,0,0.0,https://jatit.org/volumes/Vol103No24/6Vol103No...,Phanintorn Suaprae (First Author) และ Vitsanu ...,Corresponding Author,0.0
8,3/19/2026 13:16:14,vitsanu.nit@mahidol.ac.th,The Development of Mockumentary Short Film to ...,2569 (2026),0.0,Q4,0,0.0,https://redfame.com/journal/index.php/jets/art...,Chudanat Sudthongkhong (First Author) and Vits...,Corresponding Author,0.0
9,3/19/2026 13:21:21,vitsanu.nit@mahidol.ac.th,Components and Indicators of the Cyber Wellnes...,2568 (2025),0.0,0,Q4,0.0,https://ieeexplore.ieee.org/abstract/document/...,Daruwan Srikaew (First Author) and Vitsanu Nit...,Corresponding Author,0.0
10,3/19/2026 13:23:15,vitsanu.nit@mahidol.ac.th,An LLM-Powered Virtual Assistant for Authoring...,2568 (2025),0.0,0,Q4,0.0,https://ieeexplore.ieee.org/abstract/document/...,Chacharin Lertyosbordin (First Author) and Vit...,Corresponding Author,0.0

In [12]:
def categorize_author_publications(author_df):
    """
    Categorize author's publications by publication type.
    
    Input: DataFrame from author_value[name]
    Output: Dictionary with categories as keys and list of publications as values
    """
    categories = {
        'Q1': [],
        'Q2': [],
        'Q3': [],
        'Q4': [],
        'TCI1': [],
        'TCI2': [],
        'International Conference': [],
        'National Conference': [],
        'Other': []
    }
    
    # Map column names to categories
    column_mapping = {
        'ประเภทบทความ [วารสารไทย (TCI1-TCI2)]': 'Thai Journal',
        'ประเภทบทความ [วารสารนานาชาติ (Q1-Q4 หรืออื่นๆ)]': 'International Journal',
        'ประเภทบทความ [ประชุมวิชาการระดับนานาชาติ (International Conference)]': 'International Conference',
        'ประเภทบทความ [ประชุมวิชาการระดับชาติ (National Conference)]': 'National Conference'
    }
    
    for idx, row in author_df.iterrows():
        title = row.get('ชื่อเรื่อง', '')
        year = row.get('ปีที่ตีพิมพ์ พศ. (คศ.)', '')
        role = ''
        
        # Find author role from any author column
        for col in author_df.columns:
            if 'ชื่ออาจารย์และสถานะผู้แต่งหนังสือ' in col:
                role = row.get(col, '')
                if role and role != 0:
                    break
        
        # Determine publication category
        thai_journal = row.get('ประเภทบทความ [วารสารไทย (TCI1-TCI2)]', 0)
        intl_journal = row.get('ประเภทบทความ [วารสารนานาชาติ (Q1-Q4 หรืออื่นๆ)]', 0)
        intl_conf = row.get('ประเภทบทความ [ประชุมวิชาการระดับนานาชาติ (International Conference)]', 0)
        natl_conf = row.get('ประเภทบทความ [ประชุมวิชาการระดับชาติ (National Conference)]', 0)
        
        pub_info = {
            'title': title,
            'year': year,
            'role': role
        }
        
        # Categorize the publication
        if intl_journal and intl_journal != 0:
            if str(intl_journal).startswith('Q1'):
                categories['Q1'].append(pub_info)
            elif str(intl_journal).startswith('Q2'):
                categories['Q2'].append(pub_info)
            elif str(intl_journal).startswith('Q3'):
                categories['Q3'].append(pub_info)
            elif str(intl_journal).startswith('Q4'):
                categories['Q4'].append(pub_info)
            else:
                categories['Q4'].append(pub_info)
        elif thai_journal and thai_journal != 0:
            if str(thai_journal).startswith('TCI1'):
                categories['TCI1'].append(pub_info)
            elif str(thai_journal).startswith('TCI2'):
                categories['TCI2'].append(pub_info)
        elif intl_conf and intl_conf != 0:
            categories['International Conference'].append(pub_info)
        elif natl_conf and natl_conf != 0:
            categories['National Conference'].append(pub_info)
        elif title != 0 and title != '':
            categories['Other'].append(pub_info)
    
    # Remove empty categories
    return {k: v for k, v in categories.items() if v}


# Example usage with an author - output as DataFrame
categorized = categorize_author_publications(author_value[name])

# Convert to DataFrame
rows = []
for category, publications in categorized.items():
    for pub in publications:
        rows.append({
            'Category': category,
            'Title': pub['title'],
            'Year': pub['year'],
            'Role': pub['role']
        })

df_categorized = pd.DataFrame(rows).sort_values('Year', ascending=True).reset_index(drop=True)
df_categorized

,Category,Title,Year,Role
0,Q2,Using Virtual Reality and Conversational AI to...,2568 (2025),Corresponding Author
1,Q3,Development of Low-Cost PLC Training Kit for E...,2568 (2025),Corresponding Author
2,Q3,Conversational AI-Powered VR Development Model...,2568 (2025),EIC
3,Q3,Development of Intelligent Advisory System wit...,2568 (2025),Corresponding Author
4,Q4,Design of the System Architecture of Competenc...,2568 (2025),Corresponding Author
5,International Conference,The 3D-POD Model for AI-Driven Institutional T...,2568 (2025),EIC
6,International Conference,Online Learner Achievement and Satisfaction on...,2568 (2025),EIC
7,International Conference,Components and Indicators of the Cyber Wellnes...,2568 (2025),Corresponding Author
8,International Conference,An LLM-Powered Virtual Assistant for Authoring...,2568 (2025),Corresponding Author
9,Q4,The Development of Mockumentary Short Film to ...,2569 (2026),Corresponding Author

In [13]:
# Process all authors and export to single CSV
all_author_rows = []

for author_name, author_df in author_value.items():
    # Skip if author has no data
    if isinstance(author_df, pd.DataFrame) and len(author_df) > 0:
        # Categorize publications for this author
        categorized = categorize_author_publications(author_df)
        
        # Add each publication to the combined list
        for category, publications in categorized.items():
            for pub in publications:
                all_author_rows.append({
                    'Author': author_name,
                    'Category': category,
                    'Title': pub['title'],
                    'Year': pub['year'],
                    'Role': pub['role']
                })

# Create combined DataFrame and sort by author name and year
df_all_authors = pd.DataFrame(all_author_rows)
if len(df_all_authors) > 0:
    df_all_authors = df_all_authors.sort_values(['Author', 'Year'], ascending=[True, True]).reset_index(drop=True)
    
    # Export to CSV
    df_all_authors.to_csv('author_publications_categorized.csv', index=False, encoding='utf-8-sig')
    print(f"Exported {len(df_all_authors)} publications from {df_all_authors['Author'].nunique()} authors")
    
    df_all_authors
else:
    print("No publications found for any authors")

Exported 43 publications from 8 authors

In [14]:
df_all_authors

,Author,Category,Title,Year,Role
0,ดร.ปกรณ์กิตติ์ ม่วงประสิทธิ์,TCI1,"ปกรณ์กิตติ์ ม่วงประสิทธิ์, ศิริณา จิตต์จรัส แล...",2564 (2021),First Author
1,ดร.ปกรณ์กิตติ์ ม่วงประสิทธิ์,TCI1,The Scenario of Cooperation for Developing Loc...,2566 (2023),EIC
2,ดร.ปกรณ์กิตติ์ ม่วงประสิทธิ์,TCI1,กิจกรรมการเรียนรู้แบบมีส่วนร่วมอย่างสร้างสรรค์...,2566 (2023),First Author
3,ดร.ปกรณ์กิตติ์ ม่วงประสิทธิ์,TCI1,การพัฒนารูปแบบการเรียนรู้สู่สังคมคุณธรรมสำหรับ...,2567 (2024),First Author
4,ดร.รติรส จันทรสมดี,TCI2,Online participatory communication design for ...,2565 (2022),First Author
5,ดร.รติรส จันทรสมดี,TCI1,Problem and challenged of persons with disabil...,2566 (2023),Corresponding Author
6,ดร.รติรส จันทรสมดี,Q1,A closer look at Thailand’s COVID-19 pandemic ...,2567 (2024),EIC
7,ดร.รติรส จันทรสมดี,Q2,Developing a Policy Model to Support Family Ca...,2567 (2024),0
8,ดร.รติรส จันทรสมดี,TCI1,Problems and needs of persons with disabilitie...,2567 (2024),Corresponding Author
9,ดร.รติรส จันทรสมดี,International Conference,COVID-19 Pandemic and Its Impact on the Health...,2567 (2024),EIC
10,ดร.รติรส จันทรสมดี,Q4,The role of communication and information acce...,2568 (2025),Corresponding Author
11,ดร.รติรส จันทรสมดี,International Conference,Unveiling the Potential of a Critical Thinking...,2568 (2025),Corresponding Author
12,ดร.วิษณุ นิตยธรรมกุล,Q2,Using Virtual Reality and Conversational AI to...,2568 (2025),Corresponding Author
13,ดร.วิษณุ นิตยธรรมกุล,Q3,Development of Low-Cost PLC Training Kit for E...,2568 (2025),Corresponding Author
14,ดร.วิษณุ นิตยธรรมกุล,Q3,Conversational AI-Powered VR Development Model...,2568 (2025),EIC
15,ดร.วิษณุ นิตยธรรมกุล,Q3,Development of Intelligent Advisory System wit...,2568 (2025),Corresponding Author
16,ดร.วิษณุ นิตยธรรมกุล,Q4,Design of the System Architecture of Competenc...,2568 (2025),Corresponding Author
17,ดร.วิษณุ นิตยธรรมกุล,International Conference,The 3D-POD Model for AI-Driven Institutional T...,2568 (2025),EIC
18,ดร.วิษณุ นิตยธรรมกุล,International Conference,Online Learner Achievement and Satisfaction on...,2568 (2025),EIC
19,ดร.วิษณุ นิตยธรรมกุล,International Conference,Components and Indicators of the Cyber Wellnes...,2568 (2025),Corresponding Author
20,ดร.วิษณุ นิตยธรรมกุล,International Conference,An LLM-Powered Virtual Assistant for Authoring...,2568 (2025),Corresponding Author
21,ดร.วิษณุ นิตยธรรมกุล,Q4,The Development of Mockumentary Short Film to ...,2569 (2026),Corresponding Author
22,ดร.สุภชาญ ตรัยตรึงศ์สกุล,Q1,Developing a Graph-Paper Embosser for Visually...,2569 (2026),First Author
23,ดร.สุภชาญ ตรัยตรึงศ์สกุล,Q1,A Survey of Graph-Based Assistive Technologies...,2569 (2026),First Author
24,พญ.วัชรา ริ้วไพบูลย์,Q1,UNav: An Infrastructure-Independent Vision-Bas...,2565 (2022),EIC
25,พญ.วัชรา ริ้วไพบูลย์,Q2,Factors influencing making a choice and access...,2565 (2022),Corresponding Author
26,พญ.วัชรา ริ้วไพบูลย์,Q2,A Smart Service System for Spatial Intelligenc...,2566 (2023),EIC
27,พญ.วัชรา ริ้วไพบูลย์,Q1,Feasibility of online psychosocial interventio...,2567 (2024),Corresponding Author
28,พญ.วัชรา ริ้วไพบูลย์,Q2,Evaluating the efficacy of UNav: A computer vi...,2567 (2024),EIC
29,พญ.วัชรา ริ้วไพบูลย์,Q1,How inclusive were strategies to prevent the s...,2568 (2025),EIC
30,พญ.วัชรา ริ้วไพบูลย์,Q1,Assessing Thailand’s mental health services to...,2568 (2025),Corresponding Author
31,พญ.วัชรา ริ้วไพบูลย์,Q3,Enhancing Recovery-Oriented Systems with Psych...,2569 (2026),Corresponding Author
32,รศ.ดร.อาดัม นีละไพจิตร,TCI1,ผลของโปรแกรมการให้คำปรึกษารายบุคคลแบบออนไลน์ต่...,2567 (2024),EIC
33,รศ.ดร.อาดัม นีละไพจิตร,National Conference,กลไกการพัฒนาระบบการจ้างงานคนพิการเชิงสังคม,2567 (2024),First Author
34,รศ.ดร.อาดัม นีละไพจิตร,National Conference,Jobs Able :แพลตฟอร์มการเตรียมคนพิการ สู่การจ้า...,2567 (2024),First Author
35,รศ.ดร.อาดัม นีละไพจิตร,TCI1,นโยบายด้านคนพิการ สู่การพัฒนาการตระหนักรู้ความ...,2568 (2025),First Author
36,รศ.ดร.อาดัม นีละไพจิตร,National Conference,Jobs for All: Application การจ้างงานคนพิการ,2568 (2025),First Author
37,ราษฏร์ บุญญา,TCI2,การพัฒนาบทเรียนอิเล็กทรอนิกส์เพื่อส่งเสริมทักษ...,2565 (2022),First Author
38,ราษฏร์ บุญญา,TCI1,The Development of E-Learning on Topic of Impa...,2566 (2023),First Author
39,ศ.ดร.ทวี เชื้อสุวรรณทวี,Q1,A closer look at Thailand’s COVID-19 pandemic ...,2567 (2024),First Author
40,ศ.ดร.ทวี เชื้อสุวรรณทวี,Q2,Development of a transition service model for ...,2568 (2025),Corresponding Author
41,ศ.ดร.ทวี เชื้อสุวรรณทวี,Q3,Advancing vocational education and training fo...,2568 (2025),Corresponding Author
42,ศ.ดร.ทวี เชื้อสุวรรณทวี,Q4,Effects of parent-implemented intervention for...,2568 (2025),EIC

In [15]:
pd.DataFrame(temp)

,Timestamp,Email Address,ชื่อเรื่อง,ปีที่ตีพิมพ์ พศ. (คศ.),ประเภทบทความ [ประชุมวิชาการระดับนานาชาติ (International Conference)],DOI หรือ URL ที่ตีพิมพ์,ระบุชื่อผู้แต่ง ที่เป็นFirst Author และ/หรือ Corresponding Author ที่ไม่ได้เป็นอาจารย์ในสถาบันราชสุดา หรือเป็นนักศึกษา โปรดใส่ สถานะผู้แต่ง เช่น สนธิ ลิ้ม (First Author) และ ศ.ดร.อำไพ ลอดยาว (Corresponding Author),ชื่ออาจารย์และสถานะผู้แต่งหนังสือ [ดร.วิษณุ นิตยธรรมกุล]
0,3/19/2026 13:23:15,vitsanu.nit@mahidol.ac.th,An LLM-Powered Virtual Assistant for Authoring...,2568 (2025),Q4,https://ieeexplore.ieee.org/abstract/document/...,Chacharin Lertyosbordin (First Author) and Vit...,Corresponding Author

In [ ]:
author_value['ดร.วิษณุ นิตยธรรมกุล']

In [ ]:
author_value[name]

In [ ]:
author_value[name].update(pd.DataFrame(temp))

In [18]:
faculty_members()

['นพ.สมเกียรติ ลีละศิธร',
 'พญ.วัชรา ริ้วไพบูลย์',
 'ศ.ดร.ทวี  เชื้อสุวรรณทวี',
 'รศ.ดร.อาดัม นีละไพจิตร',
 'รศ.ดร.ณัฏฐนียา โตรักษา',
 'ผศ.ดร.อารี ภาวสุทธิไพศิฐ',
 'ผศ.ดร.ธีรศักดิ์ ศรีสุรกุล',
 'ผศ.ดร.เจนจิรา เจนจิตรวาณิช',
 'ดร.รติรส จันทรสมดี',
 'ดร.อิศวรา ศิริรุ่งเรือง',
 'ดร.ธรรม จตุนาม',
 'ดร.รุจิรา สงขาว',
 'ดร.ปรเมศวร์ บุญยืน',
 'ดร.ปกรณ์กิตติ์ ม่วงประสิทธิ์',
 'ดร.สุนันทา ขลิบทอง',
 'ดร.วรางคณา รัชตะวรรณ',
 'ดร.ญาณิศา เนียรนาทตระกูล',
 'ดร.สุภชาญ ตรัยตรึงศ์สกุล',
 'ดร.วิษณุ นิตยธรรมกุล',
 'พฤหัส เปรมสมิทธิ์',
 'ราษฏร์ บุญญา',
 'กุลยา ไทรงาม',
 'ณัฐวิชญ์ ศุภสินธุ์',
 'พชร นิลมณี',
 'สิรินทรา ฤทธิเดช',
 'สร้อยทอง หยกสุริยันต์',
 'ภัทรานิษฐ สงประชา',
 'อาจารย์พิเศษ (ภายนอกม.มหิดล)',
 'อาจารย์พิเศษ (ภายนอกคณะแพทย์ฯรามา ม.มหิดล)']

In [21]:
def get_publication(publication):
    # publication = get_worksheet(worksheet,3)

    Year = publication.columns[3]
    TCI = publication.columns[4]
    Qs  = publication.columns[5]
    IntConf  = publication.columns[6]
    NatConf = publication.columns[7]
    Role = publication.columns[7]

    lecturers = faculty_members()[:-2]

    rec_year = defaultdict(lambda:defaultdict(int))
    for i,a in enumerate(publication[Year]):
        if len(publication[TCI].iloc[i]) > 0:
            rec_year[a][publication[TCI].iloc[i]]+=1
        elif len(publication[Qs].iloc[i]) > 0:
            rec_year[a][publication[Qs].iloc[i]]+=1
        elif len(publication[IntConf].iloc[i]) > 0:
            rec_year[a][publication[IntConf].iloc[i]]+=1
        elif len(publication[NatConf].iloc[i]) > 0:
            rec_year[a][publication[IntConf].iloc[i]]+=1

    df = pd.DataFrame(rec_year).T.fillna(0).astype(int)

    # Get current column names and sort them
    sorted_column_names = sorted(df.columns)

    # Reindex the DataFrame with the sorted column names
    df_sorted = df[sorted_column_names].sort_index()
    ax = df_sorted.plot(kind='bar', stacked=True, figsize=(8, 6), colormap='viridis')
    fig = ax.get_figure()
    st.pyplot(fig)
    return publication,df_sorted

In [22]:
publication,df = get_publication(publication)
df = df.reset_index().rename(columns={'index':'ปี'})
df.to_csv('publication.csv')
# st.write(df)

2026-05-10 15:56:36.673 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

2026-05-10 15:56:36.991 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-10 15:56:37.156
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run /home/vscode/.local/lib/python3.11/site-packages/ipykernel_launcher.py [ARGUMENTS]
2026-05-10 15:56:37.158 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-05-10 15:56:37.161 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

In [23]:
publication

,Timestamp,Email Address,ชื่อเรื่อง,ปีที่ตีพิมพ์ พศ. (คศ.),ประเภทบทความ [วารสารไทย (TCI1-TCI2)],ประเภทบทความ [วารสารนานาชาติ (Q1-Q4 หรืออื่นๆ)],ประเภทบทความ [ประชุมวิชาการระดับนานาชาติ (International Conference)],ประเภทบทความ [ประชุมวิชาการระดับชาติ (National Conference)],DOI หรือ URL ที่ตีพิมพ์,ชื่ออาจารย์และสถานะผู้แต่งหนังสือ [นพ.สมเกียรติ ลีละศิธร],...,ชื่ออาจารย์และสถานะผู้แต่งหนังสือ [กุลยา ไทรงาม],ชื่ออาจารย์และสถานะผู้แต่งหนังสือ [ณัฐวิชญ์ ศุภสินธุ์],ชื่ออาจารย์และสถานะผู้แต่งหนังสือ [พชร นิลมณี],ชื่ออาจารย์และสถานะผู้แต่งหนังสือ [สิรินทรา ฤทธิเดช],ชื่ออาจารย์และสถานะผู้แต่งหนังสือ [ดร.สุภชาญ ตรัยตรึงศ์สกุล],ระบุชื่อผู้แต่ง ที่เป็นFirst Author และ/หรือ Corresponding Author ที่ไม่ได้เป็นอาจารย์ในสถาบันราชสุดา หรือเป็นนักศึกษา โปรดใส่ สถานะผู้แต่ง เช่น สนธิ ลิ้ม (First Author) และ ศ.ดร.อำไพ ลอดยาว (Corresponding Author),ชื่ออาจารย์และสถานะผู้แต่งหนังสือ [ดร.วิษณุ นิตยธรรมกุล],ชื่ออาจารย์และสถานะผู้แต่งหนังสือ [สร้อยทอง หยกสุริยันต์],ชื่ออาจารย์และสถานะผู้แต่งหนังสือ [ภัทรานิษฐ สงประชา],ประเภทบทความ [Proceedings]
0,9/17/2025 23:02:31,vitsanu.nit@mahidol.ac.th,Using Virtual Reality and Conversational AI to...,2568 (2025),,Q2,,,https://doi.org/10.11114/smc.v13i3.7683,,...,,,,,,Kridsanapong Lertbumroongchai (First Author),Corresponding Author,,,
1,9/17/2025 23:05:36,vitsanu.nit@mahidol.ac.th,Development of Low-Cost PLC Training Kit for E...,2568 (2025),,Q3,,,https://repository.li.mahidol.ac.th/handle/123...,,...,,,,,,Natt Siriwattananon (First Author),Corresponding Author,,,
2,9/17/2025 23:08:50,vitsanu.nit@mahidol.ac.th,The 3D-POD Model for AI-Driven Institutional T...,2568 (2025),,,Q3,,https://link.springer.com/chapter/10.1007/978-...,,...,,,,,,Sirinuch Sararuch (First Author),EIC,,,
3,9/17/2025 23:14:34,vitsanu.nit@mahidol.ac.th,Online Learner Achievement and Satisfaction on...,2568 (2025),,,Q4,,https://ieeexplore.ieee.org/document/11129412,,...,,,,,,Thakorn Yuvijit (First Author),EIC,,,
4,9/19/2025 14:59:38,ras.boo@mahidol.ac.th,การพัฒนาบทเรียนอิเล็กทรอนิกส์เพื่อส่งเสริมทักษ...,2565 (2022),TCI2,,,,https://ejournals.swu.ac.th/index.php/rise/art...,,...,,,,,,,,,,
5,9/19/2025 11:05:59,ras.boo@mahidol.ac.th,The Development of E-Learning on Topic of Impa...,2566 (2023),TCI1,,,,https://so03.tci-thaijo.org/index.php/RSjourna...,,...,,,,,,,,,,
6,10/27/2025 9:57:07,pakornkit.mua@mahidol.ac.th,"ปกรณ์กิตติ์ ม่วงประสิทธิ์, ศิริณา จิตต์จรัส แล...",2564 (2021),TCI1,,,,https://so02.tci-thaijo.org/index.php/suedujou...,,...,,,,,,,,,,
7,10/27/2025 10:01:35,pakornkit.mua@mahidol.ac.th,The Scenario of Cooperation for Developing Loc...,2566 (2023),TCI1,,,,https://www.journal.nu.ac.th/JCDR/article/view...,,...,,,,,,รศ.ดร.ชูชีพ พุทธประเสริฐ,,,,
8,10/27/2025 10:02:12,pakornkit.mua@mahidol.ac.th,กิจกรรมการเรียนรู้แบบมีส่วนร่วมอย่างสร้างสรรค์...,2566 (2023),TCI1,,,,https://so03.tci-thaijo.org/index.php/jssr/art...,,...,,,,,,,,,,
9,10/27/2025 10:02:59,pakornkit.mua@mahidol.ac.th,การพัฒนารูปแบบการเรียนรู้สู่สังคมคุณธรรมสำหรับ...,2567 (2024),TCI1,,,,https://so02.tci-thaijo.org/index.php/banditvi...,,...,,,,,,,,,,
10,11/4/2025 12:52:38,vitsanu.nit@mahidol.ac.th,Conversational AI-Powered VR Development Model...,2568 (2025),,Q3,,,10.14569/IJACSA.2025.0161073,,...,,,,,,Jenasama Srihirun (First Author) และ Kridsanap...,EIC,,,
11,11/4/2025 12:54:59,vitsanu.nit@mahidol.ac.th,Design of the System Architecture of Competenc...,2568 (2025),,อื่นๆ,,,10.5539/hes.v15n4p422,,...,,,,,,Thongchai Arunchai (First Author),Corresponding Author,,,
12,2/6/2026 11:19:59,tavee.che@mahidol.ac.th,Advancing vocational education and training fo...,2568 (2025),,Q3,,,https://so02.tci-thaijo.org/index.php/hasss/ar...,,...,,,,,,,,,,
13,2/6/2026 11:22:28,tavee.che@mahidol.ac.th,Development of a transition service model for ...,2568 (2025),,Q2,,,https://jsser.org/index.php/jsser/article/view...,,...,,,,,,,,,,
14,2/6/2026 11:28:18,tavee.che@mahidol.ac.th,Effects of parent-implemented intervention for...,2568 (2025),,Q4,,,https://www.e-cacd.org/detail/30011881,,...,,,,,,"Wanicharoen, N",,,,
15,2/6/2026 11:30:52,tavee.che@mahidol.ac.th,A closer look at Thailand’s COVID-19 pandemic ...,2567 (2024),,Q1,,,https://journals.sagepub.com/doi/10.1177/00208...,,...,,,,,,,,,,
16,2/6/2026 11:33:23,tavee.che@mahidol.ac.th,Problems and needs of persons with disabilitie...,2567 (2024),TCI1,,,,https://so05.tci-thaijo.org/index.php/sujthai/...,,...,,,,,,,,,,
17,2/6/2026 11:35:32,tavee.che@mahidol.ac.th,Developing a Policy Model to Support Family Ca...,2567 (2024),,Q2,,,https://so03.tci-thaijo.org/index.php/jpss/art...,,...,,,,,,"Suna, N",,,,
18,2/10/2026 9:35:15,adam.nee@mahidol.ac.th,นโยบายด้านคนพิการ สู่การพัฒนาการตระหนักรู้ความ...,2568 (2025),TCI1,,,,https://so07.tci-thaijo.org/index.php/tft/arti...,,...,,,,,,,,,,
19,2/10/2026 9:39:41,adam.nee@mahidol.ac.th,Jobs for All: Application การจ้างงานคนพิการ,2568 (2025),,,,อื่นๆ,https://cuent2026.com/,,...,,,,,,,,,,
20,2/10/2026 10:36:43,adam.nee@mahidol.ac.th,ผลของโปรแกรมการให้คำปรึกษารายบุคคลแบบออนไลน์ต่...,2567 (2024),TCI1,,,,https://so03.tci-thaijo.org/index.php/RSjourna...,,...,,,,,,ชาลิณี ขันทะ (นศ. First Author),,,,
21,2/10/2026 10:39:09,adam.nee@mahidol.ac.th,กลไกการพัฒนาระบบการจ้างงานคนพิการเชิงสังคม,2567 (2024),,,,อื่นๆ,https://www.engagementthailand.org/20240318,,...,,,,,,,,,,
22,2/10/2026 10:40:57,adam.nee@mahidol.ac.th,Jobs Able :แพลตฟอร์มการเตรียมคนพิการ สู่การจ้า...,2567 (2024),,,,อื่นๆ,https://ncpd2024.udru.ac.th/,,...,,,,,,,,,,
23,2/10/2026 15:22:22,supachan.tra@mahidol.ac.th,Developing a Graph-Paper Embosser for Visually...,2569 (2026),,Q1,,,DOI - 10.1080/17483107.2026.2629602,,...,,,,,First Author,,,,,
24,2/12/2026 8:36:46,ratirot.cha@mahidol.ac.th,Online participatory communication design for ...,2565 (2022),TCI2,,,,https://so06.tci-thaijo.org/index.php/jcosci/a...,,...,,,,,,,,,,
25,2/12/2026 8:43:44,ratirot.cha@mahidol.ac.th,Problem and challenged of persons with disabil...,2566 (2023),TCI1,,,,https://so04.tci-thaijo.org/index.php/swjourna...,,...,,,,,,,,,,
26,2/12/2026 8:45:37,ratirot.cha@mahidol.ac.th,A closer look at Thailand’s COVID-19 pandemic ...,2567 (2024),,Q1,,,https://doi.org/10.1177/00208728241269788,,...,,,,,,,,,,
27,2/12/2026 8:46:49,ratirot.cha@mahidol.ac.th,The role of communication and information acce...,2568 (2025),,อื่นๆ,,,https://dcidj.uog.edu.et/index.php/up-j-dcbrid...,,...,,,,,,,,,,
28,2/12/2026 9:05:03,ratirot.cha@mahidol.ac.th,COVID-19 Pandemic and Its Impact on the Health...,2567 (2024),,,อื่นๆ,อื่นๆ,-,,...,,,,,,,,,,
29,2/12/2026 9:01:45,ratirot.cha@mahidol.ac.th,Unveiling the Potential of a Critical Thinking...,2568 (2025),,,อื่นๆ,,-,,...,,,,,,,,,,
30,2/18/2026 11:02:42,supachan.tra@mahidol.ac.th,A Survey of Graph-Based Assistive Technologies...,2569 (2026),,Q1,,,-,,...,,,,,First Author,,,,,
31,2/20/2026 5:50:02,wachara16@gmail.com,Factors influencing making a choice and access...,2565 (2022),,Q2,,,https://doi:10.1108/IJHRH-04-2022-0028,,...,,,,,,,,,,
32,2/20/2026 9:10:44,wachara16@gmail.com,UNav: An Infrastructure-Independent Vision-Bas...,2565 (2022),,Q1,,,https://doi.org/10.3390/s22228894,,...,,,,,,,,,,
33,2/20/2026 5:58:36,wachara16@gmail.com,A Smart Service System for Spatial Intelligenc...,2566 (2023),,Q2,,,https://doi.org/10.1186/s13063-023-07173-8,,...,,,,,,,,,,
34,2/20/2026 6:02:04,wachara16@gmail.com,Evaluating the efficacy of UNav: A computer vi...,2567 (2024),,Q2,,,https://doi.org/10.1080/10400435.2024.2382113,,...,,,,,,,,,,
35,2/20/2026 9:12:35,wachara16@gmail.com,Feasibility of online psychosocial interventio...,2567 (2024),,Q1,,,doi:10.1177/00207640241264656,,...,,,,,,,,,,
36,2/20/2026 6:09:44,wachara16@gmail.com,How inclusive were strategies to prevent the s...,2568 (2025),,Q1,,,https://doi.org/10.1186/s12939-025-02482-7,,...,,,,,,,,,,
37,2/20/2026 6:11:57,wachara16@gmail.com,Assessing Thailand’s mental health services to...,2568 (2025),,Q1,,,https://doi.org/10.1016/j.ajp.2025.104608,,...,,,,,,,,,,
38,2/20/2026 6:15:01,wachara16@gmail.com,Enhancing Recovery-Oriented Systems with Psych...,2569 (2026),,Q3,,,https://doi.org/10.1007/s40737-025-00519-2,,...,,,,,,,,,,
39,3/19/2026 13:12:42,vitsanu.nit@mahidol.ac.th,Development of Intelligent Advisory System wit...,2568 (2025),,Q3,,,https://jatit.org/volumes/Vol103No24/6Vol103No...,,...,,,,,,Phanintorn Suaprae (First Author) และ Vitsanu ...,Corresponding Author,,,
40,3/19/2026 13:16:14,vitsanu.nit@mahidol.ac.th,The Development of Mockumentary Short Film to ...,2569 (2026),,Q4,,,https://redfame.com/journal/index.php/jets/art...,,...,,,,,,Chudanat Sudthongkhong (First Author) and Vits...,Corresponding Author,,,
41,3/19/2026 13:21:21,vitsanu.nit@mahidol.ac.th,Components and Indicators of the Cyber Wellnes...,2568 (2025),,,Q4,,https://ieeexplore.ieee.org/abstract/document/...,,...,,,,,,Daruwan Srikaew (First Author) and Vitsanu Nit...,Corresponding Author,,,
42,3/19/2026 13:23:15,vitsanu.nit@mahidol.ac.th,An LLM-Powered Virtual Assistant for Authoring...,2568 (2025),,,Q4,,https://ieeexplore.ieee.org/abstract/document/...,,...,,,,,,Chacharin Lertyosbordin (First Author) and Vit...,Corresponding Author,,,

In [24]:
def classify_publication(publication):  

    NAMES = []
    
    for n in publication.columns:
        if 'ชื่ออาจารย์และสถานะผู้แต่งหนังสือ' in n:
            NAMES.append(n) 

    for t in publication.columns:
        if 'วารสารไทย (TCI1-TCI2)' in t: publication.rename(columns={t:'วารสารไทย'}, inplace=True)
        elif 'วารสารนานาชาติ (Q1-Q4 หรืออื่นๆ)' in t: publication.rename(columns={t:'วารสารนานาชาติ'}, inplace=True)
        elif 'ประชุมวิชาการระดับนานาชาติ' in t: publication.rename(columns={t:'ประชุมวิชาการระดับนานาชาติ'}, inplace=True)
        elif 'ประชุมวิชาการระดับชาติ' in t: publication.rename(columns={t:'ประชุมวิชาการระดับชาติ'}, inplace=True)

    name_paper = defaultdict(list)
    for name in NAMES:
        papers = []
        for i,(role,TCI,Q,conf_int,conf_nat) in enumerate(zip(publication[name],
                                                            publication['วารสารไทย'],
                                                            publication['วารสารนานาชาติ'],
                                                            publication['ประชุมวิชาการระดับนานาชาติ'],
                                                            publication['ประชุมวิชาการระดับชาติ'])):
            if role in ['First Author', 'Corresponding Author']:
                papers+=[TCI+Q+conf_int+conf_nat]
        name_paper[name.replace('ชื่ออาจารย์และสถานะผู้แต่งหนังสือ [','').replace(']','')] = papers

    categories = ['Q1','Q2','Q3','Q4','TCI1','TCI2','อื่นๆ']
    blanktable = pd.DataFrame(np.zeros((len(name_paper.keys()), len(categories)),dtype=int), columns=categories)
    blanktable['name']=name_paper.keys()


    for idx, (name, papers) in enumerate(name_paper.items()):
        for paper in papers:
            for cat in categories:
                if cat in paper:
                    blanktable.loc[idx, cat] += 1
    
    # Reorder columns with 'name' first
    blanktable = blanktable[['name'] + [col for col in blanktable.columns if col != 'name']]
    
    # blanktable.to_csv('publication_classified.csv')

    return blanktable

In [25]:
def get_publications_by_author(publication):
    """
    Create a dictionary where:
    - Key: author name (First Author or Corresponding Author)
    - Value: list of tuples (year, title, publication_type)
    """
    
    # Find author columns
    NAMES = []
    for n in publication.columns:
        if 'ชื่ออาจารย์และสถานะผู้แต่งหนังสือ' in n:
            NAMES.append(n)
    
    # Rename journal/conference columns for easier processing
    pub_copy = publication.copy()
    for t in pub_copy.columns:
        if 'วารสารไทย (TCI1-TCI2)' in t: 
            pub_copy.rename(columns={t:'วารสารไทย'}, inplace=True)
        elif 'วารสารนานาชาติ (Q1-Q4 หรืออื่นๆ)' in t: 
            pub_copy.rename(columns={t:'วารสารนานาชาติ'}, inplace=True)
        elif 'ประชุมวิชาการระดับนานาชาติ' in t: 
            pub_copy.rename(columns={t:'ประชุมวิชาการระดับนานาชาติ'}, inplace=True)
        elif 'ประชุมวิชาการระดับชาติ' in t: 
            pub_copy.rename(columns={t:'ประชุมวิชาการระดับชาติ'}, inplace=True)
    
    author_publications = defaultdict(list)
    
    # Get year and title columns
    year_col = 'ปีที่ตีพิมพ์ พศ. (คศ.)'
    title_col = 'ชื่อเรื่อง'
    
    # Process each row
    for idx, row in pub_copy.iterrows():
        year = row.get(year_col, '')
        title = row.get(title_col, '')
        
        # Determine publication type (Q or TCI category)
        pub_type = 'อื่นๆ'
        for category in ['Q1', 'Q2', 'Q3', 'Q4', 'TCI1', 'TCI2']:
            combined_text = (str(row.get('วารสารไทย', '')) + 
                           str(row.get('วารสารนานาชาติ', '')) +
                           str(row.get('ประชุมวิชาการระดับนานาชาติ', '')) +
                           str(row.get('ประชุมวิชาการระดับชาติ', '')))
            if category in combined_text:
                pub_type = category
                break
        
        # Process each author
        for name_col in NAMES:
            role = row.get(name_col, '')
            if role in ['First Author', 'Corresponding Author','EIC']:
                if role == 'First Author': role = 'FA'
                elif role == 'Corresponding Author': role = 'CA'
                # Extract author name from column name
                author_name = name_col.replace('ชื่ออาจารย์และสถานะผู้แต่งหนังสือ [', '').replace(']', '')
                # Add publication tuple (year, title, type)
                author_publications[author_name].append((year, pub_type, role, title))
    
    return dict(author_publications)


# Export author_pubs to CSV
def export_author_publications_to_csv(author_pubs, filename):
    """
    Export author publications dictionary to CSV file
    Format: Author, Year, Publication Type, Title
    """
    rows = []
    for author, publications in author_pubs.items():
        for year, pub_type, role, title in publications:
            rows.append({
                'Author': author,
                'Year': year,
                'Publication Type': pub_type,
                'Role': role,
                'Title': title
            })
    
    df = pd.DataFrame(rows)
    df.to_csv(filename, index=False, encoding='utf-8-sig')
    print(f"Exported {len(rows)} publications to {filename}")
    return df

# Test the function
author_pubs = get_publications_by_author(publication)
df_export = export_author_publications_to_csv(author_pubs, 'author_publications.csv')

Exported 43 publications to author_publications.csv

In [35]:
theses

,Timestamp,Email Address,ชื่อ- นามสกุล (นักศึกษา),รหัส (นักศึกษา),ชื่อหัวข้อวิทยานิพนธ์,อาจารย์ที่ปรึกษาหลัก / อาจารย์ที่ปรึกษาร่วม [นพ.สมเกียรติ ลีละศิธร],อาจารย์ที่ปรึกษาหลัก / อาจารย์ที่ปรึกษาร่วม [พญ.วัชรา ริ้วไพบูลย์],อาจารย์ที่ปรึกษาหลัก / อาจารย์ที่ปรึกษาร่วม [ศ.ดร.ทวี เชื้อสุวรรณทวี],อาจารย์ที่ปรึกษาหลัก / อาจารย์ที่ปรึกษาร่วม [รศ.ดร.อาดัม นีละไพจิตร],อาจารย์ที่ปรึกษาหลัก / อาจารย์ที่ปรึกษาร่วม [รศ.ดร.ณัฏฐนียา โตรักษา],...,อาจารย์ที่ปรึกษาหลัก / อาจารย์ที่ปรึกษาร่วม [ณัฐวิชญ์ ศุภสินธุ์],อาจารย์ที่ปรึกษาหลัก / อาจารย์ที่ปรึกษาร่วม [พชร นิลมณี],อาจารย์ที่ปรึกษาหลัก / อาจารย์ที่ปรึกษาร่วม [สิรินทรา ฤทธิเดช],อาจารย์ที่ปรึกษาหลัก / อาจารย์ที่ปรึกษาร่วม [ดร.สุภชาญ ตรัยตรึงศ์สกุล],"ถ้าอาจารย์ที่ปรึกษาร่วม อยู่นอกสังกัดสถาบันราชสุดา โปรดระบุ ชื่อ-นามสกุล เช่น รศ.ดร. หนึ่ง นามหนึ่ง, ดร.สอง นามสอง, ...","สถานะของความก้าวหน้าวิทยานิพนธ์\n(ลำดับไล่จาก สอบโครงร่างแล้ว ไปถึง อยู่ระหว่างรอเผยแพร่ตีพิมพ์)\nหมายเหตุ \n1. ""อยู่ระหว่างขอ IRB"" ให้ตีความครอบคลุมถึง ""กำลังร่าง IRB"" / ""กำลังแก้ไข IRB"" \n2. ""กำลังเก็บข้อมูล"" ให้ตีความครอบคลุมถึง ""ได้ขอ IRB ผ่านแล้ว จึงดำเนินการเก็บข้อมูลได้"" แต่ยังเก็บไม่เสร็จ\n3. ""อยู่ระหว่างการวิเคราะห์ข้อมูล"" รวมถึงกระบวนการ ""การอภิปรายผล และ/หรือสรุปผล""\n4. ลำดับ ""อยู่ระหว่างรอเผยแพร่การตีพิมพ์"" และ ""สอบป้องกันวิทยานิพนธ์แล้ว"" ให้เลือกสถานการณ์ปัจจุบัน เนื่องจาก จะมีการบันทึกข้อมูลไว้ในระบบ เช่น สอบป้องกันแล้วรอผลตีพิมพ์ (เลือก-->รอตีพิมพ์) หรือ ยังไม่สอบป้องกัน แต่รอตีพิมพ์ (--> เลือกรอตีพิมพ์) ก็เลือกสิ่งที่เป็นปัจจุบัน",หลักสูตร,อาจารย์ที่ปรึกษาหลัก / อาจารย์ที่ปรึกษาร่วม [ดร.วิษณุ นิตยธรรมกุล],อาจารย์ที่ปรึกษาหลัก / อาจารย์ที่ปรึกษาร่วม [สร้อยทอง หยกสุริยันต์],อาจารย์ที่ปรึกษาหลัก / อาจารย์ที่ปรึกษาร่วม [ภัทรานิษฐ สงประชา]
10,8/28/2025 15:35:12,nattawan.fun@mahidol.ac.th,น.ส.สโรชา ชัยแจ้ง,6338210,การพัฒนารูปแบบการมีส่วนร่วมของผู้ปกครองในการเป...,,,,,,...,,,,,,อยู่ระหว่างขอ IRB,ปริญญาเอก-ปรัชญาดุษฎีบัณฑิต สาขาวิชาการพัฒนาคุ...,,,
11,8/28/2025 15:36:47,nattawan.fun@mahidol.ac.th,นายวีระชัย จิตภักดี,6436532,การพัฒนาโปรแกรมการจัดการตนเองแบบบูรณาการโดยใช้...,,,Main Advisor,,,...,,,,,ศ.นพ.รุ่งโรจน์ พิทยศิริ,อยู่ระหว่างขอ IRB,ปริญญาเอก-ปรัชญาดุษฎีบัณฑิต สาขาวิชาการพัฒนาคุ...,,,
12,8/28/2025 15:38:52,nattawan.fun@mahidol.ac.th,น.ส.วิพุธ เคหะสุวรรณ,6438155,การพัฒนารูปแบบการใช้ดนตรีที่บ้านโดยญาติผู้ดูแล...,,,Main Advisor,,,...,,,,,ผศ.ดร.นัทธี เชียงชะนา,กำลังเก็บข้อมูล,ปริญญาเอก-ปรัชญาดุษฎีบัณฑิต สาขาวิชาการพัฒนาคุ...,,,
13,8/28/2025 16:04:59,nattawan.fun@mahidol.ac.th,น.ส.อรวรรณ เจือจาน,5837354,รูปแบบการช่วยเหลือระยะแรกเริ่มสำหรับเด็กพิการผ...,,,Main Advisor,,,...,,,,,รศ.ดร.ดารณี ศักดิ์ศิริผล,อยู่ระหว่างรอเผยแพร่วิทยานิพนธ์,ปริญญาเอก-ปรัชญาดุษฎีบัณฑิต สาขาวิชาการพัฒนาคุ...,,,
14,8/28/2025 16:06:23,nattawan.fun@mahidol.ac.th,นางกนกวรรณ อุสันโน,5837356,ข้อพิจารณาในการออกแบบ บ้านเพื่อการอยู่อาศัยตลอ...,,,Co advisor,,,...,,,,,รศ.ดร.วิฑูรย์ เหลียวรุ่งเรือง,อยู่ระหว่างรอเผยแพร่วิทยานิพนธ์,ปริญญาเอก-ปรัชญาดุษฎีบัณฑิต สาขาวิชาการพัฒนาคุ...,,,
15,8/28/2025 16:07:47,nattawan.fun@mahidol.ac.th,นายจักรพงศ์ พิพิธภักดี,5837353,การพัฒนารูปแบบการให้บริการอุปกรณ์ สิ่งอำนวยควา...,,,Co advisor,,,...,,,,,ผศ.ดร.บรรยงค์ รุ่งเรืองด้วยบุญ,อยู่ระหว่างรอเผยแพร่วิทยานิพนธ์,ปริญญาเอก-ปรัชญาดุษฎีบัณฑิต สาขาวิชาการพัฒนาคุ...,,,
16,8/28/2025 16:08:51,nattawan.fun@mahidol.ac.th,นางอรอนงค์ สงเจริญ,5837357,\tการพัฒนารูปแบบการจัดบริการเปลี่ยนผ่านจากอุดม...,,,,,,...,,,,,ผศ.ดร.พิมพา ขจรธรรม,อยู่ระหว่างรอเผยแพร่วิทยานิพนธ์,ปริญญาเอก-ปรัชญาดุษฎีบัณฑิต สาขาวิชาการพัฒนาคุ...,,,
17,8/28/2025 16:10:24,nattawan.fun@mahidol.ac.th,น.ส.แพรว เอี่ยมน้อย,6036242,กระบวนการบังคับใช้กฎหมายเพื่อเพิ่มโอกาสการมีงา...,,Main Advisor,,,,...,,,,,ผศ.พญ.กมลเนตร วรรณเสวก และ ศ.ดร.กิติพัฒน์ นนทป...,อยู่ระหว่างรอเผยแพร่วิทยานิพนธ์,ปริญญาเอก-ปรัชญาดุษฎีบัณฑิต สาขาวิชาการพัฒนาคุ...,,,
18,8/28/2025 16:11:20,nattawan.fun@mahidol.ac.th,น.ส.กนกทิพย์ สว่างใจธรรม,6136263,การพัฒนาคุณภาพชีวิตในผู้สูงอายุพิการทางร่างกาย...,,Main Advisor,,,,...,,,,,รศ.ดร.รัชนี สรรเสริญ,อยู่ระหว่างรอเผยแพร่วิทยานิพนธ์,ปริญญาเอก-ปรัชญาดุษฎีบัณฑิต สาขาวิชาการพัฒนาคุ...,,,
19,8/28/2025 16:13:18,nattawan.fun@mahidol.ac.th,นายพงศ์พิชญ์ แสนศรี,6137713,การประเมินผลการใช้แนวทางปฏิบัติการให้บริการเทค...,,Main Advisor,,,,...,,,,,1. อ.ดร.วีระแมน นิยมพล 2. ผศ.ดร.ศิตาพร ยังคง 3...,อยู่ระหว่างรอเผยแพร่วิทยานิพนธ์,ปริญญาเอก-ปรัชญาดุษฎีบัณฑิต สาขาวิชาการพัฒนาคุ...,,,
20,1/19/2026 10:14:46,natchanan.vat@mahidol.ac.th,นายเนรมิต ศรีสังข์ทอง,6336554 RAES/M,ปัจจัยที่มีผลต่อการตัดสินใจเลือกเรียนของนักศึก...,,,,,,...,,,,,ผู้ช่วยศาสตราจารย์ ดร.นัทธี เชียงชะนา,อยู่ระหว่างขอ IRB,ปริญญาโท-ศึกษาศาสตรมหาบัณฑิต สาขาวิชาการศึกษาส...,,,
21,9/1/2025 15:16:30,natchanan.vat@mahidol.ac.th,นางสาววิภาวี ปรัชญาบำรุง,6136690 RAES/M,A SURVEY OF MUSIC INSTRUCTION FOR STUDENTS WIT...,,,,,,...,,,,,,อยู่ระหว่างขอ IRB,ปริญญาโท-ศึกษาศาสตรมหาบัณฑิต สาขาวิชาการศึกษาส...,,,
22,9/1/2025 16:15:47,natchanan.vat@mahidol.ac.th,นางสาวรัตนาภรณ์ ใจมูล,6336555 RAES/M,การพัฒนาความรู้ความเข้าใจ เรื่องพหุนาม ของนักเ...,,,,,,...,,,,,,อยู่ระหว่างขอ IRB,ปริญญาโท-ศึกษาศาสตรมหาบัณฑิต สาขาวิชาการศึกษาส...,,,
23,9/1/2025 16:18:28,natchanan.vat@mahidol.ac.th,นางสาวฐิติพร ประวัติศรีชัย,6336560 RAES/M\t,การศึกษาแนวทางการให้บริการสนับสนุนผู้เรียนด้าน...,,,,,,...,,,,,,กำลังเก็บข้อมูล,ปริญญาโท-ศึกษาศาสตรมหาบัณฑิต สาขาวิชาการศึกษาส...,,,
24,9/1/2025 16:20:38,natchanan.vat@mahidol.ac.th,นางกาญจนา สอนวิสูตร,6536122 RAES/M,การใช้การสอนเสริมตามแนวคิดพหุสัมผัส เพื่อพัฒนา...,,,,,,...,,,,,ผู้ช่วยศาสตราจารย์ ดร.นัทธี เชียงชะนา,อยู่ระหว่างขอ IRB,ปริญญาโท-ศึกษาศาสตรมหาบัณฑิต สาขาวิชาการศึกษาส...,,,
25,9/2/2025 8:41:34,natchanan.vat@mahidol.ac.th,นางสาวชลฤทัย หุ่นดี,6538070 RAES/M,การสอนเสริมความรู้ในรายวิชาภาษาไทยด้วยแนวคิดออ...,,,,,,...,,,,,,อยู่ระหว่างขอ IRB,ปริญญาโท-ศึกษาศาสตรมหาบัณฑิต สาขาวิชาการศึกษาส...,,,
26,9/2/2025 8:44:57,natchanan.vat@mahidol.ac.th,นางสาวณัชฐานันท์ ปั้นทองคำ,6538071 RAES/M,การเปรียบเทียบวิธีการช่วยเหลือด้านทักษะทางสังค...,,,,,,...,,,,,ผู้ช่วยศาสตราจารย์ ดร.นัทธี เชียงชะนา,อยู่ระหว่างขอ IRB,ปริญญาโท-ศึกษาศาสตรมหาบัณฑิต สาขาวิชาการศึกษาส...,,,
28,5/8/2026 15:01:49,siriwan.vit@mahidol.ac.th,นาย\tคุณากร\tสุวรรณเนตร,6236228,การศึกษาสถานการณ์การเข้าถึงหนังสืออิเล็กทรอนิก...,,,,,,...,,,,,ผู้ช่วยศาสตราจารย์ ดร. ปารณีย์ วิสุทธิพันธุ์\n,อยู่ระหว่างรอเผยแพร่การตีพิมพ์,ปริญญาโท-ศิลปศาสตรมหาบัณฑิต สาขาวิชาการพัฒนาคุ...,,,
35,5/8/2026 14:59:10,siriwan.vit@mahidol.ac.th,น.ส.\tกฤติกานต์\tพลงาม,6536501,ศึกษาความสัมพันธ์ระหว่างปัจจัยที่เกี่ยวข้องและ...,,,,,,...,,,,,ผู้ช่วยศาสตราจารย์ ดร. ปารณีย์ วิสุทธิพันธุ์\n,สำเร็จการศึกษาแล้วเมื่อ 2568/ ภาค 2),ปริญญาโท-ศิลปศาสตรมหาบัณฑิต สาขาวิชาการพัฒนาคุ...,,,
36,1/7/2026 11:48:01,nattawan.fun@mahidol.ac.th,น.ส.ณัฐนรี แคซิลด้า เอี่ยมสถาพร,6336146,การทำความเข้าใจ เรื่องการจ้างงานผู้ที่มีความหล...,,,,,Main Advisor,...,,,,,ผศ.นพ.อัศวิน นาคพงศ์พันธุ์,กำลังเก็บข้อมูล,ปริญญาเอก-ปรัชญาดุษฎีบัณฑิต สาขาวิชาการพัฒนาคุ...,,,
37,5/8/2026 14:49:03,siriwan.vit@mahidol.ac.th,น.ส.\tปิยบุตร\tเกตุวิริยะกุล,6336708,การพัฒนาแบบประเมินพฤติกรรมการปรับตัวสำหรับผู้ป...,,,,Main Advisor,,...,,,,,,สำเร็จการศึกษาแล้ว เมื่อ 2568/ ภาค 2),ปริญญาโท-ศิลปศาสตรมหาบัณฑิต สาขาวิชาการพัฒนาคุ...,,,
38,1/7/2026 14:20:24,nattawan.fun@mahidol.ac.th,นายชวัลส์ภัสร์ กวินนิธิพร,6636362,ภูมิหลังทางดนตรีและรูปแบบดนตรีบำบัดเพื่อส่งเสร...,,,Main Advisor,,,...,,,,,ผศ.ดร.นัทธี เชียงชะนา,อยู่ระหว่างขอ IRB,ปริญญาเอก-ปรัชญาดุษฎีบัณฑิต สาขาวิชาการพัฒนาคุ...,,,
39,5/8/2026 14:05:56,siriwan.vit@mahidol.ac.th,นางพิมพร\tนพยนต์เลิศ,6536120,ศึกษาการให้รถนั่งคนพิการทางการเคลื่อนไหวตามแนว...,,,,Main Advisor,,...,,,,,ผศ. ดร. ปารณีย์ วิสุทธิพันธุ์,สอบป้องกันวิทยานิพนธ์แล้ว,ปริญญาโท-ศิลปศาสตรมหาบัณฑิต สาขาวิชาการพัฒนาคุ...,,,
40,1/8/2026 21:34:19,siriwan.vit@mahidol.ac.th,น.ส.\tดารินทร์\tสิงห์สาธร,6536121,การเข้าถึงแหล่งทุน การประกอบอาชีพของคนพิการซ้อ...,,,,Main Advisor,,...,,,,,ผศ.ดร. ปารณีย์ วิสุทธิพันธุ์,อยู่ระหว่างการวิเคราะห์ข้อมูล,ปริญญาโท-ศิลปศาสตรมหาบัณฑิต สาขาวิชาการพัฒนาคุ...,,,
41,1/8/2026 21:43:08,siriwan.vit@mahidol.ac.th,น.ส.\tนารี\tคงพินิจ,6537780,การพัฒนาโมเดล 3 มิติพูดได้เพื่อส่งเสริมผลสัมฤท...,,,,,,...,,,,,ผศ.ดร. ปารณีย์ วิสุทธิพันธุ์,สอบป้องกันวิทยานิพนธ์แล้ว,ปริญญาโท-ศิลปศาสตรมหาบัณฑิต สาขาวิชาการพัฒนาคุ...,,,
42,1/8/2026 22:00:26,siriwan.vit@mahidol.ac.th,น.ส.\tณัฐชานันท์\tไตรวัฒนวงษ์,6636152,การศึกษาการเตรียมความพร้อมเข้าสู่สังคมสูงวัยที...,,,,,,...,,,,,,สอบโครงร่างแล้ว,ปริญญาโท-ศิลปศาสตรมหาบัณฑิต สาขาวิชาการพัฒนาคุ...,,,
43,1/8/2026 22:14:23,siriwan.vit@mahidol.ac.th,น.ส.\tพัฒน์ปภาวัณย์\tอ่าวเจริญ \t\t,6236227,ศึกษารูปแบบการจ้างงานคนพิการทางการเห็นตามมาตรา...,,,,,,...,,,,,ผศ.ดร. พัลลภา ปีติสันต์,อยู่ระหว่างรอเผยแพร่การตีพิมพ์,ปริญญาโท-ศิลปศาสตรมหาบัณฑิต สาขาวิชาการพัฒนาคุ...,,,
44,5/8/2026 14:09:16,siriwan.vit@mahidol.ac.th,น.ส.\tจิดาภา\tกฤษณา \t\t,6237467,การศึกษาการจัดบริการฟื้นฟูสมรรถภาพทางการเห็นแล...,,,,,Main Advisor,...,,,,,รศ.(พิเศษ) นพ. ภาคภูมิ คัมภีร์พันธุ์,ตีพิมพ์เผยแพร่แล้ว รออนุมัติสำเร็จการศึกษา,ปริญญาโท-ศิลปศาสตรมหาบัณฑิต สาขาวิชาการพัฒนาคุ...,,,
45,5/8/2026 14:47:37,siriwan.vit@mahidol.ac.th,น.ส.\tจุฑามณี\tทองสมบัติพาณิช,6237468,การศึกษาความสามารถจัดการตนเองในการทำกิจวัตรประ...,,Co advisor,,,Main Advisor,...,,,,,,อยู่ระหว่างรอเผยแพร่การตีพิมพ์,ปริญญาโท-ศิลปศาสตรมหาบัณฑิต สาขาวิชาการพัฒนาคุ...,,,
46,1/19/2026 10:23:44,natchanan.vat@mahidol.ac.th,นางสาวน้ำทิพย์ หวังวิวัฒน์เจริญ,6638028\tRAES/M,การศึกษาปัจจัยที่ส่งผลต่อสุขภาพจิตของครูผู้สอน...,,Co advisor,,,,...,,,,,,กำลังเก็บข้อมูล,ปริญญาโท-ศึกษาศาสตรมหาบัณฑิต สาขาวิชาการศึกษาส...,,,
47,1/19/2026 10:26:18,natchanan.vat@mahidol.ac.th,นายกิตติภณ ลิ้มคุณธรรม,6638027 RAES/M,การพัฒนาความคล่องแคล่วในการอ่านของผู้เรียนชาวไ...,,,,,,...,,,,,,อยู่ระหว่างขอ IRB,ปริญญาโท-ศึกษาศาสตรมหาบัณฑิต สาขาวิชาการศึกษาส...,,,
48,5/8/2026 15:52:23,natchanan.vat@mahidol.ac.th,นางสาวบุษกร สันเทพ,6136693,การสำรวจการให้บริการช่วยเหลือระยะแรกเริ่มที่บ้...,,,,,,...,,,,,,อยู่ระหว่างขอ IRB,ปริญญาโท-ศึกษาศาสตรมหาบัณฑิต สาขาวิชาการศึกษาส...,,,
49,5/8/2026 15:54:57,natchanan.vat@mahidol.ac.th,นายอภิวัฒน์ เตชะสุริยวรกุล,6236401,การพัฒนานวัตกรรมสื่อการเรียนรู็เรื่องการวางแผน...,,,,,,...,,,,,,อยู่ระหว่างขอ IRB,ปริญญาโท-ศึกษาศาสตรมหาบัณฑิต สาขาวิชาการศึกษาส...,,,
50,5/8/2026 15:57:52,natchanan.vat@mahidol.ac.th,นางสาวพรรณิภา วรรณยิ่ง,6337910,การพัฒนาทักษะการดูแลสำหรับผู้ปกครองของเด็กที่ม...,,,,,,...,,,,,,อยู่ระหว่างขอ IRB,ปริญญาโท-ศึกษาศาสตรมหาบัณฑิต สาขาวิชาการศึกษาส...,,,
51,5/8/2026 16:00:36,natchanan.vat@mahidol.ac.th,นางสาวรสสุคนธ์ เชี่ยวปัญญานันท์,6736515,การมีส่วนร่วมของผู้เกี่ยวข้องต่อการจัดการศึกษา...,,,,,,...,,,,,,อยู่ระหว่างขอ IRB,ปริญญาโท-ศึกษาศาสตรมหาบัณฑิต สาขาวิชาการศึกษาส...,,,
52,5/8/2026 16:04:33,natchanan.vat@mahidol.ac.th,นางสาวชนาพิชญ์ จินตกะวงค์,6738566,ผลของการใช้ชุดกิจกรรมการเรียนรู้เพื่อเสริมสร้า...,,Co advisor,,,,...,,,,,,อยู่ระหว่างขอ IRB,ปริญญาโท-ศึกษาศาสตรมหาบัณฑิต สาขาวิชาการศึกษาส...,,,
53,5/8/2026 16:06:53,natchanan.vat@mahidol.ac.th,นางสุดาทิพย์ คัสติเนน,6738567,"EXPLORING SHADOW TEACHERS’ KNOWLEDGE, PRACTICE...",,,,,,...,,,,,รองศาสตราจารย์ ดร. โจเซฟ เซย์รัม อักเบนเยกา,อยู่ระหว่างขอ IRB,ปริญญาโท-ศึกษาศาสตรมหาบัณฑิต สาขาวิชาการศึกษาส...,,,

In [27]:
get_thesis_progression_summary(theses)

[63           -
 64           -
 58           -
 60           -
 61           -
 65           -
 62           -
 66    MA[QL]x1
 67           -
 Name: สอบโครงร่างแล้ว, dtype: str,
 63    PhD[QL]x4
 64    PhD[QL]x1
 58            -
 60            -
 61     MA[Ed]x2
 65     MA[Ed]x3
 62     MA[Ed]x1
 66    PhD[QL]x2
 67     MA[Ed]x3
 Name: อยู่ระหว่างขอ IRB, dtype: str,
 63     MA[Ed]x2
 64    PhD[QL]x1
 58            -
 60            -
 61            -
 65            -
 62            -
 66     MA[Ed]x1
 67            -
 Name: กำลังเก็บข้อมูล, dtype: str,
 63           -
 64           -
 58           -
 60           -
 61           -
 65    MA[QL]x1
 62           -
 66           -
 67           -
 Name: อยู่ระหว่างการวิเคราะห์ข้อมูล, dtype: str,
 63           -
 64           -
 58           -
 60           -
 61           -
 65    MA[QL]x2
 62           -
 66           -
 67           -
 Name: สอบป้องกันวิทยานิพนธ์แล้ว, dtype: str,
 63            -
 64            -
 58    PhD[QL]x4
 60    PhD[QL]x1
 61    PhD[QL]x2
 65            -
 62            -
 66            -
 67            -
 Name: อยู่ระหว่างรอเผยแพร่วิทยานิพนธ์, dtype: str]

In [29]:
def get_thesis_workload_new(theses):
    theses = theses.drop_duplicates(subset=['รหัส (นักศึกษา)'], keep='last')
    ST = defaultdict(lambda:defaultdict(list))
    for name in faculty_members()[:-2]:
        List = f'อาจารย์ที่ปรึกษาหลัก /  อาจารย์ที่ปรึกษาร่วม [{name}]'
        a = theses[List].value_counts()
        a = pd.DataFrame(a).reset_index().rename(columns={List:'ad-co'}).iloc[1:]
        MAIN = a[a['ad-co']=='Main Advisor']['count'].to_list()
        COAD = a[a['ad-co']=='Co advisor']['count'].to_list()
        if len(MAIN) == 0 and len(COAD) == 0:
            pass
        else:
            if len(MAIN) == 0: 
                MAIN = [0]
            ST[name]['Main Advisor'] = MAIN[0] 
            if len(COAD) == 0: 
                COAD = [0]
            ST[name]['Co advisor'] = COAD[0]
    return ST

In [32]:
ST = get_thesis_workload_new(theses)

# Plot thesis advisor workload
if isinstance(ST, dict) and len(ST) > 0:
    df_thesis_workload = pd.DataFrame(ST).T.fillna(0).astype(int)
    df_thesis_workload = df_thesis_workload[['Main Advisor','Co advisor']] if set(['Main Advisor','Co advisor']).issubset(df_thesis_workload.columns) else df_thesis_workload
    ax = df_thesis_workload.plot(kind='bar', figsize=(10, 6), stacked=False)
    ax.set_title('Thesis Advisor Workload by Faculty Member')
    ax.set_xlabel('Faculty Member')
    ax.set_ylabel('Number of Students')
    ax.legend(title='Advisor Role')
    ax.grid(axis='y', linestyle='--', alpha=0.6)
    plt.xticks(rotation=45, ha='right')
    plt.tight_layout()
    plt.show()
else:
    print('No thesis workload data available to plot.')

In [33]:
df_thesis_workload = pd.DataFrame(ST).T.fillna(0).astype(int)
df_thesis_workload = df_thesis_workload[['Main Advisor','Co advisor']] if set(['Main Advisor','Co advisor']).issubset(df_thesis_workload.columns) else df_thesis_workload
ax = df_thesis_workload.plot(kind='bar', figsize=(10, 6), stacked=False)
ax.set_title('Thesis Advisor Workload by Faculty Member')
ax.set_xlabel('Faculty Member')
ax.set_ylabel('Number of Students')
ax.legend(title='Advisor Role')
ax.grid(axis='y', linestyle='--', alpha=0.6)
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

In [34]:
df_thesis_workload

                           Main Advisor  Co advisor
พญ.วัชรา ริ้วไพบูลย์                  3           3
ศ.ดร.ทวี  เชื้อสุวรรณทวี              4           2
รศ.ดร.อาดัม นีละไพจิตร                3           0
รศ.ดร.ณัฏฐนียา โตรักษา                3           0
ผศ.ดร.ธีรศักดิ์ ศรีสุรกุล             9           5
ดร.รติรส จันทรสมดี                    0           3
ดร.อิศวรา ศิริรุ่งเรือง               3           8
ดร.รุจิรา สงขาว                       2           1
ดร.ปรเมศวร์ บุญยืน                    0           1
ดร.สุนันทา ขลิบทอง                    4           4
ดร.วรางคณา รัชตะวรรณ                  1           3